# Generated by Django 5.2.7 on 2025-10-13 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='adj_high',
        ),
    ]
