# Generated by Django 5.2.7 on 2025-10-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_rename_price_stock_adj_high'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='adj_high',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
