# Generated by Django 5.2.7 on 2025-10-23 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_stock_adj_high'),
    ]

    operations = [
        migrations.CreateModel(
            name='EODStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=6)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change', models.DecimalField(decimal_places=4, max_digits=12)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('time_epoch_ms', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'EOD_stocks',
                'db_table_comment': 'Table used for EOD stocks, stores once a day at close',
                'ordering': ['-time_epoch_ms'],
                'unique_together': {('symbol', 'time_epoch_ms')},
            },
        ),
        migrations.CreateModel(
            name='IntradayStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=6)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('high', models.DecimalField(decimal_places=4, max_digits=12)),
                ('low', models.DecimalField(decimal_places=4, max_digits=12)),
                ('change', models.DecimalField(decimal_places=4, max_digits=12)),
                ('open', models.DecimalField(decimal_places=4, max_digits=12)),
                ('time_epoch_ms', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'intraday_stocks',
                'db_table_comment': 'Table used for intraday stocks, stores each minute',
                'ordering': ['-time_epoch_ms'],
                'unique_together': {('symbol', 'time_epoch_ms')},
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
