# Generated by Django 5.2.7 on 2025-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_eodstock_intradaystock_delete_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eodstock',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='intradaystock',
            name='change',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
