# Generated by Django 5.2.7 on 2025-11-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_eodstock_change_alter_intradaystock_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockIntradayStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(db_index=True, max_length=6)),
                ('close', models.DecimalField(decimal_places=4, max_digits=12)),
                ('time_epoch_ms', models.BigIntegerField(db_index=True)),
            ],
            options={
                'db_table': 'mock_intraday_stocks',
                'db_table_comment': 'Mock table used for intraday stocks, stores each minute',
                'ordering': ['-time_epoch_ms'],
                'unique_together': {('symbol', 'time_epoch_ms')},
            },
        ),
    ]
