# Generated by Django 5.2.7 on 2025-12-23 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_mockintradaystock'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_id', models.CharField(max_length=100, unique=True)),
                ('link', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('symbol', models.CharField(db_index=True, max_length=6)),
                ('pub_date', models.DateTimeField(db_index=True)),
                ('image_url', models.URLField(max_length=500)),
                ('source_name', models.CharField(db_index=True, max_length=100)),
                ('source_url', models.URLField()),
                ('fetched_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'news_articles',
                'db_table_comment': 'table used to store news articles fetched from API',
                'ordering': ['-pub_date'],
            },
        ),
    ]
