export const COMPANY_NAMES = {
    'AAPL': 'Apple',
    'ABBV': 'AbbVie',
    'ABT': 'Abbott Laboratories',
    'ADBE': 'Adobe',
    'AMD': 'Advanced Micro Devices',
    'AMZN': 'Amazon.com',
    'AVGO': 'Broadcom',
    'AXP': 'American Express',
    'BAC': 'Bank of America',
    'BLK': 'BlackRock',
    'BRK.B': 'Berkshire Hathaway (Class B)',
    'CAT': 'Caterpillar',
    'CMCSA': 'Comcast',
    'COST': 'Costco Wholesale',
    'CRM': 'Salesforce',
    'CSCO': 'Cisco Systems',
    'CVX': 'Chevron',
    'DIS': 'Walt Disney',
    'GE': 'General Electric',
    'GOOG': 'Alphabet (Class C)',
    'GS': 'Goldman Sachs Group',
    'HD': 'Home Depot',
    'INTU': 'Intuit',
    'JNJ': 'Johnson & Johnson',
    'JPM': 'JPMorgan Chase',
    'KO': 'Coca-Cola',
    'LLY': 'Eli Lilly',
    'MA': 'Mastercard',
    'MCD': "McDonald's",
    'META': 'Meta Platforms',
    'MRK': 'Merck',
    'MS': 'Morgan Stanley',
    'MSFT': 'Microsoft',
    'MU': 'Micron Technology',
    'NFLX': 'Netflix',
    'NOW': 'ServiceNow',
    'NVDA': 'NVIDIA',
    'ORCL': 'Oracle',
    'PEP': 'PepsiCo',
    'PG': 'Procter & Gamble',
    'QCOM': 'Qualcomm',
    'TMO': 'Thermo Fisher Scientific',
    'TMUS': 'T-Mobile US',
    'TSLA': 'Tesla',
    'TXN': 'Texas Instruments',
    'UNH': 'UnitedHealth Group',
    'V': 'Visa',
    'WFC': 'Wells Fargo',
    'WMT': 'Walmart',
    'XOM': 'Exxon Mobil',
}